# -*- coding: utf-8 -*-
"""project-100.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rz3oHxJfZ5y03MvnsSiomyhwJfR79pX6
"""

class ATM:
  def __init__(self,cardNumber, pinNumber):
    self.cardnumber = cardNumber
    self.pinnumber = pinNumber

  def withdraw(self):
    print("withdraw done")

  def balance(self):
    print("this is your balance")

account = ATM(987654321, 1234)
account.withdraw()
account.balance()